export const SAVE_BASIC_DETAILS_REQUEST =
  "SAVE_RESTAURANT_SESSION_NAME_REQUEST";
export const SAVE_BASIC_DETAILS_SUCCESS = "SAVE_BASIC_DETAILS_SUCCESS";
export const SAVE_BASIC_DETAILS_FAILURE = "SAVE_BASIC_DETAILS_FAILURE";

export const POST_DATA_REQUEST = "POST_DATA_REQUEST";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAILURE = "POST_DATA_FAILURE";
export const POST_ONBOARDING_DATA_REQUEST = "POST_ONBOARDING_DATA_REQUEST";
export const POST_ONBOARDING_DATA_SUCCESS = "POST_ONBOARDING_DATA_SUCCESS";
export const POST_ONBOARDING_DATA_FAILURE = "POST_ONBOARDING_DATA_FAILURE";

export const POST_DINEIN_DATA_REQUEST = "POST_DINEIN_DATA_REQUEST";
export const POST_DINEIN_DATA_SUCCESS = "POST_DINEIN_DATA_SUCCESS";
export const POST_DINEIN_DATA_FAILURE = "POST_DINEIN_DATA_FAILURE";

export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const LOCATION_ID = "LOCATION_ID";

export const POST_DELIVERY_DATA_REQUEST = "POST_DELIVERY_DATA_REQUEST";
export const POST_DELIVERY_DATA_SUCCESS = "POST_DELIVERY_DATA_SUCCESS";
export const POST_DELIVERY_DATA_FAILURE = "POST_DELIVERY_DATA_FAILURE";

export const POST_RESTAURANTiMAGE_DATA_REQUEST="POST_RESTAURANTiMAGE_DATA_REQUEST"
export const POST_RESTAURANTiMAGE_DATA_SUCCESS="POST_RESTAURANTiMAGE_DATA_SUCCESS"
export const POST_RESTAURANTiMAGE_DATA_FALIURE="POST_RESTAURANTiMAGE_DATA_FALIURE"
