export const POST_DELIVERY_DATA_REQUEST = "POST_DELIVERY_DATA_REQUEST"
export const POST_DELIVERY_DATA_SUCCESS = "POST_DELIVERY_DATA_SUCCESS"
export const POST_DELIVERY_DATA_FAILURE = "POST_DELIVERY_DATA_FAILURE"